name: Semantic versioning
on:
  pull_request:
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
        - 16
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6

      # GITHUB_PR_LABEL_V_MINOR was set by pr-labels-action
      - run: |
          if [ -n "$GITHUB_PR_LABEL_V_MINOR" ]; then
            git config --global user.email "ferjmoreno@gmail.com"
            git config --global user.name "Fernando Jimenez Moreno"
            git clone "https://ferjm:${{secrets.GH_PAT}}@github.com/ferjm/gh-action-branch-naming.git" 
            cd gh-actions-branch-naming
            touch version
            echo minor > version
            git add version
            git commit -m "Next release will bump minor version" || true
            git push origin main || true
          fi
