on:
  push:
    branches: # Push to following branches will trigger the workflow
      - feature/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # This may save additional git fetch roundtrip if
        # merge-base is found within latest 20 commits
        fetch-depth: 20
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: main # Change detection against merge-base with this branch
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
    - name: Comment in PR
      if: steps.filter.outputs.backend == 'true'
      uses: hollander/actions-comment-pull-request@v1
      with:
        message: 'Hello folks'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: hello world
      if: steps.filter.outputs.backend == 'true'
      run: echo "Hello world backend"
